version: '3'
services:
  api:
    restart: always
    build: ./api
    volumes: 
      - ./api:/usr/src/app/api
    ports:
      - "3023:3023"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"